Feat/controller
Milahn-Henri-Louis-Irwin-ITBSA/map-service pull request #2
Opened 2023-11-06 21:08 UTC by Irwincr13

2023-11-06 21:19 UTC, milahnmartin requested changes
Just check the return type for the getCoords method, also maybe make the name more readable as the implementation focuses on returning the size of docs with those coords.

2023-11-06 21:19 UTC, milahnmartin commented on libs/db/MapDB.ts
> +  }): Promise<MapData | number | null> {
If you are inly returning the size, then only set the return type to number and not MapData and null it will and should always only be number

2023-11-07 16:41 UTC, HenriLouw approved these changes

2023-11-08 13:18 UTC, Louis-Bat17 approved these changes
Looking good, i like that we're also including an 'other' event type option.
This helps justify our open/close principle.

2023-11-11 12:29 UTC, merged